homebrew: install: add 'group' directive to chmod command
if your group name is literally called 'user' then this command fails

Error: /Stage[main]/Homebrew::Install/Exec[set-/usr/local/share/man3-directory-inherit]: '/bin/chmod -R +a 'user:allow list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit' /usr/local/share/man3' returned 1 instead of one of [0]