Undo repository management and check only on brew
...mainly because of this error:

  err: /Stage[main]//Package[git]/ensure: change from absent to present
  failed: Execution of '/usr/local/bin/brew install git' returned 1:
  Error: Cowardly refusing to `sudo brew install'
  You can use brew with sudo, but only if the brew executable is owned by
  root.
  However, this is both not recommended and completely unsupported so do
  so at your own risk.